name: CICD

on:
  push:
    branches:
      - bala-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          touch .env
          echo "${{ secrets.DOCKER_DEMO_FILE }}" > .env

      - name: Login to Docker Hub
        run: |
          echo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Docker image
        run: docker build -t balak1696/pdfapp_cicd .

      - name: Publish image to Docker Hub
        run: docker push balak1696/pdfapp_cicd:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest  # AWS EC2 requires custom runners; adjust this if you're using a self-hosted runner
    steps:
      - name: Pull image from docker hub
        run: docker pull balak1696/pdfapp_cicd:latest
      - name: Delete old container
        run: docker rm -f pdfapp_cicd-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container balak1696/pdfapp_cicd